shell = "/bin/zsh" 

import = [
# https://github.com/alacritty/alacritty-theme
"~/.config/alacritty/themes/themes/argonaut.toml"
]

[font]
size = 14.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
    
[window]
dimensions = { columns = 120, lines = 30 }


